ALTER TABLE `Arena` ADD COLUMN `logoUrl` VARCHAR(500) NULL;
ALTER TABLE `Arena` ADD COLUMN `bannerUrl` VARCHAR(500) NULL;

CREATE TABLE `TrainerPhoto` (
  `id` VARCHAR(191) NOT NULL,
  `trainerId` VARCHAR(191) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `TrainerPhoto_trainerId_fkey` FOREIGN KEY (`trainerId`) REFERENCES `TrainerProfile` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB;

CREATE TABLE `ArenaPhoto` (
  `id` VARCHAR(191) NOT NULL,
  `arenaId` VARCHAR(191) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `ArenaPhoto_arenaId_fkey` FOREIGN KEY (`arenaId`) REFERENCES `Arena` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB;
